# -*- coding: utf-8 -*-
"""Build fifth-round external research & novelty matrix CSV (2026-09-12)."""
import csv
from pathlib import Path

ROOT = Path(r"D:\zcode-workspace\aidd-repo-work\00-当前研究\fifth_round_20260912")
out = ROOT / "外部研究与创新性矩阵.csv"

HEAD = ["compound","synonym","CAS","InChIKey","disease","target/pathway","evidence type","cell","animal","human",
        "binding","functional assay","docking only","PMID","DOI","patent","clinical pipeline","evidence level",
        "novelty conclusion","search date","database","query","source URL","assay_id/activity_id","species","construct","endpoint","notes"]

R=[]
def r(*a): R.append(list(a))
SD="2026-09-12"
r("moracin N","Moracin-N; 5-prenylmoracin M","135248-05-4","WBSCSIABHGPAMC-UHFFFAOYSA-N",
  "脑缺血（非 MASH）","Keap1/Nrf2→ferroptosis（FTH1/ACSL4↓、GSH↑）","动物+细胞机制实验",
  "原代神经元 OGD（体外）","小鼠 MCAO，脑室内 20 mg/kg/day×3d","否","否（Keap1/Nrf2 为通路激活证据，非直接结合）",
  "是（梗死体积/神经功能/铁死亡指标；ML385 阻断保护）","否","40972263","10.1016/j.phymed.2025.157253",
  "—","无（ClinicalTrials.gov 0 项）","直接机制证据（脑/神经元层）",
  "Moracin N×Nrf2/ferroptosis 已证实到脑层级；×MASH 未连接",SD,"PubMed","\"moracin N\" AND ferroptosis",
  "https://pubmed.ncbi.nlm.nih.gov/40972263/","—","Mus musculus","原代神经元/MCAO","梗死体积、FTH1、ACSL4、GSH、ML385 阻断",
  "脑室内给药不能外推口服/肝暴露；ML385 剂量摘要未给"),
r("moracin N","同上","135248-05-4","WBSCSIABHGPAMC-UHFFFAOYSA-N",
  "—（铁死亡细胞模型，非疾病）","GPX4/GSH/ROS/铁代谢","细胞机制实验","HT22 海马神经元 erastin","否","否","否",
  "是（抗铁死亡 EC50<0.50 μM；GPx4 失活抑制）","否","34281775","10.1016/j.phymed.2021.153641","—","无",
  "直接机制证据（神经元层）","同上；SLC7A11/ACSL4 逐项数值未在摘要给出",SD,"PubMed","\"moracin N\" AND (GPX4 OR ferroptosis)",
  "https://pubmed.ncbi.nlm.nih.gov/34281775/","—","HT22（小鼠）","erastin 诱导","CCK-8、DCFH-DA、GSH、FeRhoNox、qPCR/WB",""),
r("moracin N","同上","135248-05-4","WBSCSIABHGPAMC-UHFFFAOYSA-N",
  "—","芳香化酶/酪氨酸酶/脂肪酶/α-葡萄糖苷酶（非项目靶点）","生化酶抑制","否","否",
  "是（tyrosinase IC50 0.924 μM；aromatase 31.1 μM；lipase 29.7 μM；α-glucosidase 2.76 μM）","否","否","否",
  "11678652; 25461329; 25935644","10.1021/np010288l; 10.1016/j.ejmech.2014.11.047; 10.1016/j.bmcl.2015.04.045",
  "—","无","直接生化证据（无关靶点）","不构成 MASH/THR 证据；提示杂环多酚一般酶抑制背景",SD,
  "PubChem BioAssay/BindingDB","CID641376 assay summary","https://pubchem.ncbi.nlm.nih.gov/compound/641376",
  "AID357965; AID1191279; AID1191280; AID1204217","混合","无细胞酶","IC50",""),
r("moracin N","同上","135248-05-4","WBSCSIABHGPAMC-UHFFFAOYSA-N",
  "MASH/MASLD/NASH/NAFLD/肝纤维化","任意","检索边界行（未检出直接研究）","—","—","—","—","—","—","—","—",
  "仅合成专利 CN118772094B、KR101558733B1","0 项","未检出（≠无研究）",
  "空白成立：Moracin N×MASH 无直接研究（指定数据库/检索式/日期内）",SD,"PubMed/EuropePMC/CT.gov",
  "\"moracin N\" AND (MASH OR MASLD OR NASH OR NAFLD OR fatty liver OR hepatic fibrosis)",
  "raw/external/moracin_N_pubmed_disease_broad.json","—","—","—","—",
  "表述限定：'截至2026-09-12，指定数据库与检索式下未发现直接证据'"),
r("moracin N","同上","135248-05-4","WBSCSIABHGPAMC-UHFFFAOYSA-N",
  "—","THRβ/THRA/TRα/FXR","检索边界行（未检出直接实验）","—","—","—","—","—","—","—","—","—","0 项",
  "未检出（≠无研究）","H1 仅为 structure-based hypothesis；不得称 TRβ 配体",SD,"PubMed/ChEMBL/BindingDB",
  "\"moracin N\" AND (THRB OR TRβ OR THRA OR TRα OR FXR)","raw/external/moracin_N_*.json",
  "—","—","—","—","ChEMBL CHEMBL465881 无 TR 活性记录；BindingDB 无 TR 靶点"),

# ============ formononetin ============
r("formononetin","Biochanin B; 7-hydroxy-4'-methoxyisoflavone; 4'-O-methyldaidzein","485-72-3","HKQYGTCOTHHOMP-UHFFFAOYSA-N",
  "NASH（MCD 模型）","SIRT1/PGC-1α/PPARα→脂肪酸β氧化","动物机制实验（治疗性干预）","否",
  "MCD 小鼠（SIRT1/PGC1A 敲低+SRT1720/EX527 因果验证）","否","否","是（ALT/AST/TG/脂变改善；SIRT1 敲低后保护消失）",
  "否","38185065","10.1016/j.phymed.2023.155285","—","无（红车轴草营养研究 4 项，非单体 MASH）",
  "直接动物+因果干预证据（摘要级：剂量/n 未在摘要给出）",
  "疾病锚点已建立；真正增量=FXR 依赖性与 SIRT1 链的因果关系",SD,"PubMed","\"formononetin\" AND NASH",
  "https://pubmed.ncbi.nlm.nih.gov/38185065/","—","Mus musculus","MCD 膳食","ALT/AST/TG/FAO/SIRT1 通路",
  "MCD 模型转化限制：缺肥胖/胰岛素抵抗/人类代谢背景；不能写成完整模拟人类 MASH"),
r("formononetin","同上","485-72-3","HKQYGTCOTHHOMP-UHFFFAOYSA-N",
  "—","FXR（NR1H4）直接激动","体外结合+功能","AML12（报告基因）；HepG2（PA 脂毒性，非本分子）","否","否",
  "是：SPR KD 1.323×10⁻⁶（原文表单位 μmol/L，量纲按原文记录不换算）",
  "是：Ostβ 报告基因 EC50 0.1972 μmol/L；上调 Shp/Ostb mRNA","否（该文另有 Glide 对接 −9.3634）",
  "39510639","10.1016/S1875-5364(24)60706-5","—","无",
  "直接结合+功能证据（CJNM 2024，全文核对）",
  "FXR 激动为已发表事实，不是本项目新发现；本分子未进入该文 TNF-α/Fxr-siRNA/PA-HepG2 最终功能组（2/6/8/12）",
  SD,"CJNM 原文","论文 Table 1/2 全文核对",
  "https://www.cjnmcpu.com/article/doi/10.1016/S1875-5364(24)60706-5","—","AML12/纯化 FXR","OSTβ 启动子报告基因",
  "SPR/报告基因/RT-qPCR","17 候选中化合物4；17 个候选与 9 个报告基因阳性中均无 3'-methoxydaidzein"),
r("formononetin","同上","485-72-3","HKQYGTCOTHHOMP-UHFFFAOYSA-N",
  "胆汁淤积（ANIT，非 MASH）","SIRT1-FXR 胆汁酸稳态/PPARα-JNK","动物+细胞","是","ANIT 小鼠","否",
  "否（通路关联，非直接结合）","是（胆汁酸代谢基因改善）","否","30928103","10.1016/j.bbrc.2019.03.131","—","无",
  "间接机制证据","支持 FXR-SIRT1 交叉但非直接结合；早于 CJNM 2024",SD,"PubMed","\"formononetin\" AND (FXR OR cholestasis)",
  "https://pubmed.ncbi.nlm.nih.gov/30928103/","—","Mus musculus","ANIT 模型","胆汁酸基因/炎症",""),
r("formononetin","同上","485-72-3","HKQYGTCOTHHOMP-UHFFFAOYSA-N",
  "MASH/MASLD","THRβ/TRα","检索边界行（无直接 TR 实验）","—","—","—","—","—","—","—","—",
  "专利仅提取物/组分列举（CN1927876B 等）","无","未检出（≠无研究）",
  "TR 方向为空白（指定检索边界内）；其 WT docking 中位 −9.072 仅技术重复性",SD,"PubMed",
  "\"formononetin\" AND (THRB OR TRβ OR THRA OR TRα)","raw/external/formononetin_pubmed_*.json","—","—","—","—",
  "T3 敏化文献（Ariyani 2018）仅 genistein/daidzein，不迁移"),

# ============ 3'-methoxydaidzein ============
r("3'-methoxydaidzein","3-MOD; 7,4'-dihydroxy-3'-methoxyisoflavone; CHEBI:65780; CHEMBL450602","21913-98-4","MUYAUELJBWQNDH-UHFFFAOYSA-N",
  "—（疼痛模型，非肝病）","NaV1.7/NaV1.8/NaV1.3 电压门控钠通道","电生理功能实验（本体）",
  "HEK293T（rNaV1.3/1.4、hNaV1.5/1.7）；ND7/23（rNaV1.8）；原代大鼠 DRG","是：小鼠镇痛（0.26–6.5 mg/kg ip；CCI 50 mg/kg po bid×14d）","否",
  "否（功能电流抑制，非结合测定）","是：全细胞膜片钳 IC50 NaV1.7 181±14 nM；NaV1.8 397±26 nM；NaV1.3 505±46 nM；DRG TTX-s 0.71 μM",
  "否","31262454","10.1016/S1875-5364(19)30049-4","CN106822090B（抗血小板用途，非 MASH）","无",
  "直接本体功能证据（亚微摩尔）",
  "重大风险：亚微摩尔 NaV 抑制+神经系统体内活性→off-target 风险明显，不再称'便宜低风险创新'",SD,
  "PubMed/CJNM 原文","\"3'-methoxydaidzein\" AND (NaV1.7 OR NaV1.8 OR NaV1.3)",
  "https://pubmed.ncbi.nlm.nih.gov/31262454/","—","HEK293T/ND7/23/DRG/小鼠","rNaV1.3、hNaV1.7、rNaV1.8 等","IC50（全细胞电流）",
  "50 mg/kg po 120min 血浆约1.83 μM、t1/2 约10 h；NaV1.5 IC50 2.63 μM 心脏离靶；800 mg/kg ip 非致死"),
r("3'-methoxydaidzein","同上","21913-98-4","MUYAUELJBWQNDH-UHFFFAOYSA-N",
  "—","FXR/THRβ/THRA","检索边界行（未检出直接实验；CJNM 2024 已核实未覆盖）","—","—","—","—","—","—","—","—","—",
  "无","未检出（≠无研究）",
  "CJNM 2024 的 17 候选与 9 个 FXR 报告基因阳性均无 3'-MOD（已核实未测，非'近邻已测'）；TR 仅本项目 docking（纯结构假说）",
  SD,"PubMed/ChEBI/ChEMBL/CJNM 原文","\"3'-methoxydaidzein\" AND (FXR OR THRB OR THRA)",
  "raw/external/3_-methoxydaidzein_*.json","CHEMBL450602","—","—","—",
  "formononetin（C7-OH/4'-OCH3）FXR EC50 不可外推给 3'-MOD（C7-OH/4'-OH/3'-OCH3）"),
r("3'-methoxydaidzein","同上","21913-98-4","MUYAUELJBWQNDH-UHFFFAOYSA-N",
  "MASH/NASH/NAFLD","任意","检索边界行（未检出直接研究）","—","—","—","—","—","—","—","—",
  "—","无","未检出（≠无研究）","本体疾病证据空白（PMID 41344662 仅为毒性暴露成分检出；9322358 为 Tephrosia 分离）",
  SD,"PubMed","\"3'-methoxydaidzein\" AND (MASH OR NASH OR NAFLD OR fatty liver)",
  "raw/external/3_-methoxydaidzein_pubmed_disease_broad.json","—","—","—","—",""),

# ============ isorhamnetin ============
r("isorhamnetin","3'-methoxyquercetin; 3'-O-methylquercetin; quercetin 3'-methyl ether","480-19-3","IZQSVPBOUDKVDZ-UHFFFAOYSA-N",
  "NASH","脂合成/脂变/纤维化","动物疾病实验","否","NASH 小鼠口服 50 mg/kg","否","否","是（脂变/TG/肝损伤/胶原/纤维化基因改善）",
  "否","31700054","10.1038/s41598-019-52736-y","—","无（营养/生物利用度研究 3 项，非 MASH）",
  "直接动物疾病证据（摘要级）","疾病证据强；聚合/检测干扰与直接 FXR KD 未解决",SD,"PubMed",
  "\"isorhamnetin\" AND NASH","https://pubmed.ncbi.nlm.nih.gov/31700054/","—","Mus musculus","NASH 诱导膳食",
  "脂变/TG/ALT-AST/胶原/纤维化基因","'for the first time'为该文自述，不引用为项目创新点"),
r("isorhamnetin","同上","480-19-3","IZQSVPBOUDKVDZ-UHFFFAOYSA-N",
  "MASLD","FXR-胆汁酸-肠肝轴/菌群","动物+体外","是（MD+体外与 FXR interaction）","HFD-MASLD 小鼠剂量依赖+FMT","否",
  "否（interaction 为 MD+体外信号，未确认纯化受体 KD）","是（FXR 信号轴激活；16S/BA 代谢组/FMT）","否",
  "41763136","10.1016/j.phymed.2026.157987","KR101794924B1（Salicornia 来源 NAFLD，非桑/非临床）","无",
  "动物+机制证据（摘要级）","FXR 方向有信号但非直接结合；不与 moracin N 空白混同",SD,"PubMed",
  "\"isorhamnetin\" AND MASLD","https://pubmed.ncbi.nlm.nih.gov/41763136/","—","Mus musculus","HFD",
  "体重/肝脂/16S/BA/FXR 轴","多酚聚集/荧光素酶干扰需先过 Gate 0"),
r("isorhamnetin","同上","480-19-3","IZQSVPBOUDKVDZ-UHFFFAOYSA-N",
  "—","THRβ/TRα","检索边界行（无直接 TR 实验）","—","—","—","—","—","—","—","—","—","无","未检出（≠无研究）",
  "TR 方向为检索边界内空白；本项目 WT docking 中位 −8.244 仅技术重复性",SD,"PubMed",
  "\"isorhamnetin\" AND (THRB OR TRβ OR THRA OR TRα)","raw/external/isorhamnetin_pubmed_*.json","—","—","—","—",""),

# ============ biochanin A ============
r("biochanin A","Biochanin; 4'-methylgenistein; genistein 4-methyl ether","491-80-5","WUADCCWRTIWANL-UHFFFAOYSA-N",
  "—","FXR（NR1H4）直接激动","体外结合+功能","AML12（报告基因+抗炎）；HepG2（PA 脂毒性+FXR siRNA）","否","否",
  "是：SPR KD 3.469×10⁻⁷（按原文表记录）","是：Ostβ 报告基因 EC50 0.4441 μmol/L；进入 TNF-α 抗炎与 PA-HepG2+Fxr siRNA 功能验证组（化合物6）",
  "否（该文另有 Glide 对接）","39510639","10.1016/S1875-5364(24)60706-5","—","无",
  "直接结合+功能证据（CJNM 2024，全文核对）","定位=FXR 体系阳性对照，不占创新候选位",SD,"CJNM 原文",
  "论文 Table 1/2","https://www.cjnmcpu.com/article/doi/10.1016/S1875-5364(24)60706-5","—","AML12/HepG2",
  "OSTβ 报告基因/抗炎/脂毒性","报告基因/抗炎/脂毒性（多终点）","FXR-HSD17B13 等新药背景（ACS JMC 2025）不改变本分子定位"),
r("biochanin A","同上","491-80-5","WUADCCWRTIWANL-UHFFFAOYSA-N",
  "肝脂变/胰岛素抵抗（脂变级，非 MASH）","PPARα/脂代谢","动物疾病实验","是（PPARα 体外激活）",
  "DIO 小鼠膳食 0.05%×12 周","否","否","是（脂变/胰岛素抵抗改善；PPARα 转录激活）","否",
  "27145114","10.1002/mnfr.201500689","—","无（红车轴草营养研究 3 项）","直接动物证据（脂变级）",
  "疾病证据为脂变级而非 MASH 级；作为阳性对照合理",SD,"PubMed","\"biochanin A\" AND (steatosis OR NAFLD)",
  "https://pubmed.ncbi.nlm.nih.gov/27145114/","—","Mus musculus/C57BL6","HFD","组织学/代谢组/PPARα",""),
r("biochanin A","同上","491-80-5","WUADCCWRTIWANL-UHFFFAOYSA-N",
  "—","THRβ/TRα","检索边界行（无直接 TR 实验）","—","—","—","—","—","—","—","—","—","无","未检出（≠无研究）",
  "TR 方向为空白（指定检索边界内）；本项目 WT docking 中位 −9.255 仅技术重复性",SD,"PubMed",
  "\"biochanin A\" AND (THRB OR TRβ OR THRA OR TRα)","raw/external/biochanin_A_pubmed_*.json","—","—","—","—",""),

# ============ 监管锚（非候选，供背景引用） ============
r("resmetirom（监管背景锚，非候选）","Rezdiffra","—","—","非肝硬化 MASH F2–F3","THRβ 激动",
  "监管批准记录","—","—","是","—","—","—","—","—","—","FDA 加速批准 2024-03-14（NDA217785）；EMA 条件批准 2025-08-18",
  "监管事实","不得写'唯一批准'：semaglutide 2025-08 亦获批 MASH（Wegovy）",SD,"FDA/EMA 官方",
  "—","https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217785s000lbl.pdf ; https://www.ema.europa.eu/en/medicines/human/EPAR/rezdiffra",
  "—","—","—","加速批准基于组织学替代终点",""),
r("semaglutide（监管背景锚，非候选）","Wegovy","—","—","MASH F2–F3","GLP-1RA","监管批准记录","—","—","是","—","—",
  "—","—","—","—","FDA 2025-08 批准（ESSENCE）；ESSENCE NCT04822181 Phase 3",
  "监管事实","与 resmetirom 并列的已批准 MASH 药物",SD,"FDA/CT.gov","—",
  "https://www.fda.gov/drugs/news-events-human-drugs/fda-approves-treatment-serious-liver-disease-known-mash","—","—","—","—",""),
r("obeticholic acid（监管背景锚，非候选）","Ocaliva","—","—","MASH（未获批）","FXR 激动","监管记录","—","—","—","—","—",
  "—","—","—","—","FDA MASH 从未批准（CRL→REGENERATE NCT02548351 终止）；EU PBC 许可 2024-08-30 撤销",
  "监管事实","不得把 PBC 历史适应证写成 MASH 批准",SD,"CT.gov/EMA","—",
  "https://clinicaltrials.gov/study/NCT02548351 ; https://www.ema.europa.eu/en/medicines/human/EPAR/ocaliva","—","—","—","—",""),
with out.open("w",newline="",encoding="utf-8-sig") as f:
    w=csv.writer(f); w.writerow(HEAD)
    for row in R:
        assert len(row)==len(HEAD), (row[0], len(row))
        w.writerow(row)
print("rows:",len(R),"->",out)
