# -*- coding: utf-8 -*-
"""生成《抗 MASH 研究最终整合报告》正文并合并 HTML 封面。

本脚本只读取现有图表，不重跑模型、对接或数据下载。
"""
from __future__ import annotations

import hashlib
import os
import sys
from pathlib import Path

ROOT = Path(r"D:\zcode-workspace")
PDF_SKILL_DIR = Path(r"C:\Users\user\.zcode\cli\plugins\cache\zcode-plugins-official\document-skills\0.1.0\skills\pdf")
sys.path.insert(0, str(PDF_SKILL_DIR / "scripts"))

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak,
    HRFlowable,
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.lib.utils import ImageReader
from pypdf import PdfReader, PdfWriter, Transformation

TITLE = "抗 MASH 研究最终整合报告"
SUBTITLE = "干实验审计结论、候选证据分层与湿实验执行方案"
BODY_PDF = ROOT / "抗MASH研究最终整合报告_正文.pdf"
COVER_PDF = ROOT / "抗MASH研究最终整合报告_封面.pdf"
FINAL_PDF = ROOT / "抗MASH研究最终整合报告.pdf"
MARGIN = 2.0 * cm
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN

# Palette generated by pdf.py palette.cascade --title '抗MASH研究最终整合报告' --mode minimal.
PAGE_BG = colors.HexColor("#f5f4f3")
SECTION_BG = colors.HexColor("#ececeb")
CARD_BG = colors.HexColor("#e8e7e2")
TABLE_STRIPE = colors.HexColor("#efeeec")
HEADER_FILL = colors.HexColor("#4e4733")
COVER_BLOCK = colors.HexColor("#716748")
BORDER = colors.HexColor("#d5cfba")
ICON = colors.HexColor("#a79150")
ACCENT = colors.HexColor("#4926b3")
ACCENT_2 = colors.HexColor("#5ab889")
TEXT_PRIMARY = colors.HexColor("#262522")
TEXT_MUTED = colors.HexColor("#7e7c74")
SEM_SUCCESS = colors.HexColor("#437353")
SEM_WARNING = colors.HexColor("#a28240")
SEM_ERROR = colors.HexColor("#99463e")
SEM_INFO = colors.HexColor("#4a7096")


def register_fonts():
    pdfmetrics.registerFont(TTFont("Microsoft YaHei", r"C:\Windows\Fonts\msyh.ttc", subfontIndex=0))
    pdfmetrics.registerFont(TTFont("Microsoft YaHei-Bold", r"C:\Windows\Fonts\msyhbd.ttc", subfontIndex=0))
    pdfmetrics.registerFont(TTFont("SimHei", r"C:\Windows\Fonts\simhei.ttf"))
    pdfmetrics.registerFont(TTFont("Times New Roman", r"C:\Windows\Fonts\times.ttf"))
    pdfmetrics.registerFont(TTFont("Times New Roman-Bold", r"C:\Windows\Fonts\timesbd.ttf"))
    registerFontFamily(
        "Microsoft YaHei", normal="Microsoft YaHei", bold="Microsoft YaHei-Bold",
        italic="Microsoft YaHei", boldItalic="Microsoft YaHei-Bold",
    )
    registerFontFamily("SimHei", normal="SimHei", bold="SimHei", italic="SimHei", boldItalic="SimHei")
    registerFontFamily(
        "Times New Roman", normal="Times New Roman", bold="Times New Roman-Bold",
        italic="Times New Roman", boldItalic="Times New Roman-Bold",
    )


register_fonts()

st_h1 = ParagraphStyle(
    "H1", fontName="Microsoft YaHei-Bold", fontSize=17, leading=24,
    textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=8, wordWrap="CJK",
)
st_h2 = ParagraphStyle(
    "H2", fontName="Microsoft YaHei-Bold", fontSize=13.2, leading=19,
    textColor=HEADER_FILL, spaceBefore=14, spaceAfter=7, wordWrap="CJK",
)
st_h3 = ParagraphStyle(
    "H3", fontName="Microsoft YaHei-Bold", fontSize=11.2, leading=16,
    textColor=ACCENT, spaceBefore=10, spaceAfter=4, wordWrap="CJK",
)
st_body = ParagraphStyle(
    "Body", fontName="SimHei", fontSize=10.25, leading=16.4, textColor=TEXT_PRIMARY,
    alignment=TA_LEFT, spaceAfter=7, wordWrap="CJK", firstLineIndent=20.5,
)
st_body_no_indent = ParagraphStyle("BodyNoIndent", parent=st_body, firstLineIndent=0)
st_bullet = ParagraphStyle(
    "Bullet", fontName="SimHei", fontSize=10.1, leading=16.0, textColor=TEXT_PRIMARY,
    alignment=TA_LEFT, spaceAfter=4.5, wordWrap="CJK", leftIndent=13,
)
st_quote = ParagraphStyle(
    "Quote", fontName="Microsoft YaHei", fontSize=11.1, leading=18.5, textColor=HEADER_FILL,
    alignment=TA_LEFT, wordWrap="CJK", leftIndent=10, rightIndent=10,
)
st_th = ParagraphStyle(
    "TH", fontName="Microsoft YaHei-Bold", fontSize=8.9, leading=12.2,
    textColor=colors.white, alignment=TA_CENTER, wordWrap="CJK",
)
st_td = ParagraphStyle(
    "TD", fontName="SimHei", fontSize=8.55, leading=12.2,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap="CJK",
)
st_td_c = ParagraphStyle("TDC", parent=st_td, alignment=TA_CENTER)
st_cap = ParagraphStyle(
    "Caption", fontName="Microsoft YaHei", fontSize=8.2, leading=11.4, textColor=TEXT_MUTED,
    alignment=TA_CENTER, wordWrap="CJK", spaceBefore=3, spaceAfter=4,
)
st_small = ParagraphStyle(
    "Small", fontName="SimHei", fontSize=8.4, leading=12.1, textColor=TEXT_MUTED,
    alignment=TA_LEFT, wordWrap="CJK",
)
st_toc_h = ParagraphStyle(
    "TOCH", fontName="Microsoft YaHei-Bold", fontSize=16, leading=24, textColor=TEXT_PRIMARY,
    spaceAfter=12, wordWrap="CJK",
)
st_toc1 = ParagraphStyle(
    "TOC1", fontName="Microsoft YaHei-Bold", fontSize=11.2, leading=19,
    leftIndent=5, textColor=TEXT_PRIMARY, wordWrap="CJK",
)
st_toc2 = ParagraphStyle(
    "TOC2", fontName="SimHei", fontSize=9.6, leading=16.5,
    leftIndent=24, textColor=TEXT_MUTED, wordWrap="CJK",
)


class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, "bookmark_name"):
            self.notify(
                "TOCEntry",
                (
                    getattr(flowable, "bookmark_level", 0),
                    getattr(flowable, "bookmark_text", ""),
                    self.page,
                    getattr(flowable, "bookmark_key", ""),
                ),
            )


def heading(text: str, level: int) -> Paragraph:
    key = "h_" + hashlib.md5(text.encode("utf-8")).hexdigest()[:8]
    style = st_h1 if level == 0 else st_h2
    p = Paragraph(f'<a name="{key}"/><b>{text}</b>', style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def add_h1(story: list, text: str):
    story.append(CondPageBreak((PAGE_H - 2 * MARGIN) * 0.18))
    story.append(heading(text, 0))
    story.append(HRFlowable(width="100%", thickness=1.1, color=ACCENT, spaceAfter=8))


def add_h2(story: list, text: str):
    story.append(CondPageBreak((PAGE_H - 2 * MARGIN) * 0.12))
    story.append(heading(text, 1))


def add_h3(story: list, text: str):
    story.append(Paragraph(f"<b>{text}</b>", st_h3))


def p(story: list, text: str, indent: bool = True):
    story.append(Paragraph(text, st_body if indent else st_body_no_indent))


def bullets(story: list, items: list[str]):
    for item in items:
        story.append(Paragraph("-  " + item, st_bullet))


def safe_keep(elements: list):
    total = 0
    for el in elements:
        _, h = el.wrap(AVAIL_W, PAGE_H)
        total += h
    if total <= PAGE_H * 0.40:
        return [KeepTogether(elements)]
    if len(elements) >= 2:
        return [KeepTogether(elements[:2])] + elements[2:]
    return elements


def table(header: list[str], rows: list[list[str]], ratios: list[float], caption: str = "", center_cols: list[int] | None = None):
    center_cols = center_cols or []
    assert abs(sum(ratios) - 1) < 0.00001
    data = [[Paragraph(f"<b>{cell}</b>", st_th) for cell in header]]
    for row in rows:
        data.append([
            Paragraph(cell, st_td_c if j in center_cols else st_td)
            for j, cell in enumerate(row)
        ])
    t = Table(data, colWidths=[AVAIL_W * ratio for ratio in ratios], repeatRows=1, hAlign="CENTER")
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_FILL),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.45, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4.2),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4.2),
        ("TOPPADDING", (0, 0), (-1, -1), 4.2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4.2),
    ]
    for i in range(1, len(data)):
        style.append(("BACKGROUND", (0, i), (-1, i), colors.white if i % 2 else TABLE_STRIPE))
    t.setStyle(TableStyle(style))
    out = [Spacer(1, 10), t]
    if caption:
        out.append(Paragraph(caption, st_cap))
    out.append(Spacer(1, 10))
    return out


def callout(story: list, title: str, body: str, color=ACCENT):
    big = ParagraphStyle(
        "CalloutTitle_" + hashlib.md5(title.encode("utf-8")).hexdigest()[:8],
        fontName="Microsoft YaHei-Bold", fontSize=13.0, leading=19, textColor=color,
        alignment=TA_CENTER, wordWrap="CJK",
    )
    copy = ParagraphStyle(
        "CalloutBody_" + hashlib.md5(body.encode("utf-8")).hexdigest()[:8],
        fontName="SimHei", fontSize=9.7, leading=15.2, textColor=TEXT_PRIMARY,
        alignment=TA_LEFT, wordWrap="CJK",
    )
    card = Table(
        [[Paragraph(f"<b>{title}</b>", big)], [Paragraph(body, copy)]],
        colWidths=[AVAIL_W * 0.92], hAlign="CENTER",
    )
    card.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 0.8, color),
        ("LINEBEFORE", (0, 0), (0, -1), 4, color),
        ("TOPPADDING", (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 3),
        ("TOPPADDING", (0, 1), (-1, 1), 3),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 9),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))
    story.extend([Spacer(1, 8)] + safe_keep([card]) + [Spacer(1, 8)])


def figure(path: Path, caption: str, max_width: float = AVAIL_W * 0.90, max_height: float = 255):
    reader = ImageReader(str(path))
    width, height = reader.getSize()
    scale = min(max_width / width, max_height / height)
    image = Image(str(path), width=width * scale, height=height * scale, hAlign="CENTER")
    return [Spacer(1, 18)] + safe_keep([image, Paragraph(caption, st_cap)]) + [Spacer(1, 16)]


def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("Microsoft YaHei", 7.4)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 1.1 * cm, TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.0)
    canvas.line(MARGIN, PAGE_H - 1.25 * cm, PAGE_W - MARGIN, PAGE_H - 1.25 * cm)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.4)
    canvas.line(MARGIN, 1.25 * cm, PAGE_W - MARGIN, 1.25 * cm)
    canvas.setFont("Microsoft YaHei", 7.4)
    canvas.drawString(MARGIN, 0.93 * cm, "计算结题材料：结果、边界与实验决策")
    canvas.drawRightString(PAGE_W - MARGIN, 0.93 * cm, f"第 {doc.page} 页")
    canvas.restoreState()


story: list = []
toc = TableOfContents()
toc.levelStyles = [st_toc1, st_toc2]
story.append(Paragraph("<b>目 录</b>", st_toc_h))
story.append(toc)
story.append(PageBreak())

add_h1(story, "一、执行摘要")
p(story, "本报告整合 <b>mash_research</b>、<b>mash_v2_new</b>、<b>paper</b>、<b>roundtable</b> 与独立复现材料中可审计的结果。研究先后使用原始 FXR/CW-BCS、COCONUT 多靶点扩展、v5 候选治理和独立 THR-beta/FASN/SCD1 重建路线；这些路线的靶点、端点、训练数据、验证设计、筛选库、评分公式和候选范围均不同，不能拼接为一个总分或“最终总榜”。", indent=False)
callout(
    story,
    "最终科学结论",
    "仓库中没有任何候选具备直接、已完成、可追溯的抗 MASH 湿实验疗效证据。现有工作完成计算筛选、若干 docking 姿势复现、候选安全性与可得性纠错以及方法学审计；所有分子和药材结论仍是实验优先级假设，不是已验证抗 MASH lead、真实多靶点药物或单体临床有效分子。",
    SEM_ERROR,
)
p(story, "项目最稳健的成果不是筛出确定药物，而是明确了天然产物外推的结构性风险：原始 FXR 路线中 BGNN、RF 和 XGBoost 在随机切分下均较好，却在骨架隔离时同时显著退化。独立重建路线引入簇划分、Tanimoto 域评分和 split conformal 后，54 个候选仍没有一个达到自身定义的高置信域内标准。", indent=False)
story.extend(table(
    ["当前可主张", "当前不可主张"],
    [["患者表达关联、内部计算优先级、特定 docking 设置下的姿势恢复、模型外推风险", "候选的真实结合、药理方向、选择性、协同、细胞有效性、动物有效性或人体疗效"],
     ["可获取候选的湿实验进入顺序与淘汰标准", "跨路线总排名、单体临床证据、已验证抗 MASH lead"],
     ["V1 双划分失败与 V2 域外分层的定量方法学结论", "以随机切分、Vina 分数或药材来源叙事替代功能验证"]],
    [0.50, 0.50], "表 1　报告采用的证据边界"
))

add_h1(story, "二、研究演进与路线关系")
p(story, "项目在短时间内经历了主线计算交付、扩展筛选、红队纠错和独立重建。后续方法不是简单地把前序模型“升级”为同一系统，而是改变了靶点、库、端点与评价框架。因此，本报告按证据层拆分路线，以防止分数、候选和文献叙事在不兼容的体系间被错误合并。", indent=False)
story.extend(table(
    ["路线", "疾病与靶点", "主要计算方法", "可保留的成果", "最终定位"],
    [["V1：FXR/CW-BCS", "GSE135251；FXR、THR-beta、ACC1/ACC2", "池化 FXR pIC50；BGNN/RF/XGBoost；Vina；CW-BCS", "双划分性能、redocking、修正药材内部排序", "方法学主线与初步计算优先级"],
     ["COCONUT/MTS", "十个实际 RF 终点模型", "随机 80/20 QA；混合 pAct；MTS；三受体 docking", "大库探索与部分 pose 留存", "探索性 triage"],
     ["v5/圆桌", "候选安全、可得性与措辞", "人工 FINAL；证据/来源修订；候选四档", "删改高风险或不可得条目", "候选治理，不是独立验证"],
     ["独立重建", "GSE48452/GSE63067；THR-beta、FASN、SCD1", "簇划分；RF/XGB；conformal；域评分；TOPSIS", "内部簇划分指标、54 项域分层", "更严格的假设生成延伸"]],
    [0.15, 0.20, 0.25, 0.22, 0.18], "表 2　四条路线的作用与边界"
))
callout(story, "时间线的正确解释", "2026-08-17 形成 V1 计算结题评估；2026-08-18 启动扩展与独立重建方向；2026-08-23 完成复现、圆桌审计、候选重排和输出层修订。最终报告以 V1 的可审计计算主线为基础，将 V2 至 v5 作为延伸证据和下一步研究，不把它们包装为同一个连续模型。", SEM_INFO)

add_h1(story, "三、干实验方法整合")
add_h2(story, "3.1 V1：疾病关联、活性端点与模型")
p(story, "V1 使用 GSE135251 建立表达关联。保存分组元数据为 control=10、NAFL=51、NASH=155、总样本=216；README 中的 NASH=141 与分组和为 202 属过期或错误口径。差异分析实际采用 CPM 过滤、DESeq2-style median-of-ratios 归一化、log2(norm+1)、逐基因 Welch t 检验和 BH 校正，不能表述为完整 DESeq2 或 limma 流程。NR1H4/FXR 与 THRB 下降，ACACA/ACC1 与 ACACB/ACC2 上升；这些仅是表达关联，不证明靶点因果性、方向或化合物疗效。", indent=False)
p(story, "FXR 数据链为 548 条原始保存记录，449 条有效关系/单位与结构过滤后的活性记录，367 个标准化 SMILES 聚合化合物，PAINS 处理后 358 个，再经 leverage 排除后最终 354 个。原始训练数据将等号关系、nM 单位的记录转为 pIC50，并按标准化 SMILES 平均；不同 assay 语境、受体构建体和功能方向未被完整保留。", indent=False)
story.extend(table(
    ["基因", "角色", "log2FC", "调整后 p 值", "仅可解释为"],
    [["NR1H4", "FXR", "-0.285", "1.03e-02", "患者表达关联"],
     ["THRB", "THR-beta", "-0.315", "1.99e-02", "患者表达关联"],
     ["ACACA", "ACC1", "+0.897", "7.42e-05", "患者表达关联"],
     ["ACACB", "ACC2", "+0.631", "4.23e-03", "患者表达关联"]],
    [0.15, 0.18, 0.14, 0.18, 0.35], "表 3　V1 的目标基因表达关联"
))
p(story, "模型使用 Bayesian GIN、RF 与 XGBoost；同时使用随机切分与骨架隔离切分。原始适用域采用二维描述符 PCA/leverage，不能代替真正的骨架新颖性评估。对接使用 FXR、THR-beta 与 ACC2 结构，CW-BCS 将归一化预测、Vina 分数与不确定性权重进行几何组合；它是内部综合分，不包含正确药理方向、暴露、安全性、协同或疗效。", indent=False)

add_h2(story, "3.2 COCONUT 多靶点扩展")
p(story, "扩展路线需区分三个计数层：初始设计中出现过 12 个目标；原始多靶点数据实际保存 11 个 target 类别、9,195 条源记录；现有 QA 和全库评分则只显示 10 个拟合模型与 9,099 个后过滤模型输入，SQLE 未进入当前 QA 或 library_scored 输出。每靶点使用普通随机 80/20 切分，而非真正 scaffold-aware 评估。上游将 IC50、Ki 和 EC50 混为 pAct 后按 SMILES 汇总；MTS 则累加阈值以上的预测 pAct。故该路线不能从分数推断正确的多靶点药理方向或 MASH 治疗相容性。", indent=False)
bullets(story, [
    "所谓 basic ADMET 是 MW、LogP、HBD/HBA 和预测分数阈值，并非吸收、代谢、肝毒性或暴露实验。",
    "所谓稀有来源是 organism 文本规则，并非来源身份、培养可行性、供应链或药材归属核验。",
    "保存的疾病模块结果为 18 个模块、0 个 NAS 显著模块、0 个 hub gene，不能沿用强 hub 叙事。",
    "LINCS signature reversal 有脚本但无保存成功输出和决策链，不能写为已完成正交验证。",
])

add_h2(story, "3.3 独立 mash_v2_new 重建")
p(story, "独立路线更换为 THR-beta、FASN、SCD1，并采用两队列转录组、Morgan 指纹、等权 XGBoost/RF、Butina 簇划分、split conformal 和训练集最大 Tanimoto 域评分。该路线在设计上优于单纯随机切分，但簇切分只有一个顺序依赖的确定性分割；无外部测试集、无重复分割统计，conformal 区间也不能自动转移到全数据重训后的候选预测。", indent=False)
story.extend(table(
    ["靶点", "清洗后结构数", "簇切分 R2", "RMSE", "Spearman", "测试集 n"],
    [["THR-beta", "403", "0.843", "0.442", "0.895", "39"],
     ["FASN", "1,110", "0.651", "0.570", "0.785", "102"],
     ["SCD1", "239", "0.651", "0.445", "0.743", "21"]],
    [0.16, 0.18, 0.16, 0.15, 0.18, 0.17], "表 4　独立重建路线的单次簇切分内部评估", [1, 2, 3, 4, 5]
))

add_h1(story, "四、可复现结果与方法学结论")
add_h2(story, "4.1 随机切分高分不等于新骨架外推")
story.extend(table(
    ["模型", "随机切分 R2", "随机 RMSE", "骨架切分 R2", "骨架 RMSE", "骨架 Spearman"],
    [["BGNN", "0.790", "0.723", "-0.610", "1.290", "0.533"],
     ["RF", "0.845", "0.620", "0.047", "0.992", "0.641"],
     ["XGBoost", "0.811", "0.686", "-0.127", "1.079", "0.483"]],
    [0.15, 0.17, 0.17, 0.17, 0.17, 0.17], "表 5　V1 随机与骨架隔离的保存性能", [1, 2, 3, 4, 5]
))
p(story, "RF 在保存结果中是更强的点预测基线，但 BGNN、RF 和 XGBoost 都在骨架隔离中明显下降。这一共同退化排除了“仅 GNN 失败”的简单解释，支持的结论是：在该数据与化学空间下，随机切分会高估模型面对未见骨架天然产物时的表现。", indent=False)
story.extend(figure(
    ROOT / "paper" / "figs" / "fig1_dual_split.png",
    "图 1　V1 双划分模型表现。随机切分与骨架切分的差异是本项目最重要的方法学结果；图中性能不是候选疗效证据。"
))

add_h2(story, "4.2 不确定性与校准的正确边界")
p(story, "随机测试集上 sigma 与绝对误差的 Spearman 为 +0.585（p=0.00018），但骨架测试集为 +0.269（p=0.124），且名义 95% 覆盖约为 0.735。历史文件中还存在 pooled 与 test-only 两种口径；二者不是同一统计对象。random test 校准、scaffold test 评估的 M0–M4 覆盖率仅约 0.618–0.765；scaffold validation 校准的 M5 在 34 个测试样本上可达 1.000 覆盖，但 flat 区间平均半宽约 2.98 pIC50，z 型区间约 5.18–5.21 pIC50。它是保守宽区间，而不是域外精度证明。", indent=False)
story.extend(table(
    ["环境", "sigma 与绝对误差 Spearman", "p 值", "名义 95% 覆盖", "结论"],
    [["随机测试集", "+0.585", "0.00018", "1.000", "域内/近邻空间的探索性信号"],
     ["骨架测试集", "+0.269", "0.124", "0.735", "不支持可靠域外置信度"],
     ["骨架 M0–M4 后处理", "不适用", "不适用", "0.618–0.765", "未稳定恢复 95% 覆盖"],
     ["骨架 M5 校准", "不适用", "n=34", "1.000", "宽区间换取保守覆盖"]],
    [0.20, 0.23, 0.15, 0.17, 0.25], "表 6　V1 不确定性与覆盖率的可采用表述", [1, 2, 3]
))
story.extend(figure(
    ROOT / "paper" / "figs" / "fig2_recalibration.png",
    "图 2　V1 校准与重校准比较。较宽区间可提高覆盖，却降低筛选分辨率；不能把任一校准方案写成已解决域外问题。"
))

add_h2(story, "4.3 V1 药材排序与 V2 域外候选")
p(story, "CW-BCS 的收缩修正改变了小样本药材的解释。雷公藤从未缩减第 4 名降至收缩后第 9 名，说明其早期高位对覆盖条数敏感。黄连、苦参、甘草、丹参是 V1 修正后内部排序的前四，不等于它们优于 V2 的葛根/山楂或 v5 的樟芝/积雪草。", indent=False)
story.extend(table(
    ["修正后名次", "药材", "收缩分", "高置信代表/解释"],
    [["1", "黄连", "0.5288", "Epiberberine；Coptisine 仅低置信参考"],
     ["2", "苦参", "0.4577", "Kushenol E；Maackiain 仅低置信参考"],
     ["3", "甘草", "0.4426", "Licoflavanone"],
     ["4", "丹参", "0.4265", "Salvilenone"],
     ["9", "雷公藤", "0.1615", "由原始第 4 名大幅下降；不稳定"]],
    [0.16, 0.18, 0.17, 0.49], "表 7　V1 CW-BCS 收缩与置信约束后的代表结果", [0, 2]
))
story.extend(figure(
    ROOT / "paper" / "figs" / "fig4_cwbcs.png",
    "图 3　修正 CW-BCS 药材内部排序。它是指定候选库、指定权重和指定 receptor 设置下的内部优先级，不是药材疗效排名。"
))
p(story, "独立重建的 54 个候选中，39 个为 T2 边缘，15 个为 T3 域外，T1 高置信域内为 0。报告中关于最大 Tanimoto 0.17–0.29 的说法应理解为项目定义的平均域分数，而不是每个候选对每个靶点的最大相似度。", indent=False)
story.extend(figure(
    ROOT / "paper" / "figs" / "fig3_tiers.png",
    "图 4　V1 的三级标注可用于解释内部预测可靠性，不等同于真实药效。独立重建中无 T1 候选的结论同样必须以域定义为前提。"
))

add_h1(story, "五、docking、候选表与报告版本的审计边界")
add_h2(story, "5.1 docking 只能证明特定设置下的姿势恢复")
story.extend(table(
    ["体系", "保存 redocking RMSD", "可支持的结论", "不可支持的结论"],
    [["V1 FXR 3FLI/33Y", "1.2208 A", "指定设置下共晶姿势可恢复", "真实亲和力、功能方向、选择性、疗效"],
     ["V1 THR-beta 3GWS/T3", "0.4232 A", "指定设置下共晶姿势可恢复", "激动/拮抗、协同或细胞疗效"],
     ["V1 ACC2 5KKN/6U3", "0.7624 A", "指定设置下共晶姿势可恢复", "跨 receptor 分数可比性"],
     ["V2 THR-beta/OEF；FASN/ZEP", "0.56 A；1.62 A", "指定设置下共晶姿势可恢复", "三靶点功能或 MASH 疗效"]],
    [0.26, 0.16, 0.29, 0.29], "表 8　redocking 的证据范围", [1]
))
p(story, "V2 的 SCD1 未执行 docking，因此 TOPSIS 中的 SCD1 仅来自 QSAR。V2 报告关于 FASN redocking 的“pad 8 + exhaustiveness 32 重试”与保留源码不一致，正式叙事只能采用可由代码和保存 gate 支撑的设置。", indent=False)

add_h2(story, "5.2 自然领袖 docking 表与 Aspernolide D 归因")
p(story, "`natural_multitarget_leaders_docking.csv` 的 6 条记录均可映射到保存的 natlead PDBQT pose 与 multitarget_top200 源行；17 个分数与保留 pose 精度完全匹配，另 1 个 THR-beta 分数相差 0.0002，符合上游浮点精度与 PDBQT 三位小数写入的差异。文件时间也显示 pose 批次紧接 CSV 写入。", indent=False)
callout(story, "正确分类", "该表是“原始 Vina pose 支撑强、但候选选择和 CSV 生成的可执行溯源不完整”的历史导出。它可以保留为计算姿势/分数记录，不能被升级为完整可重放的自然产物筛选流程，更不能作为结合、功能或疗效验证。", SEM_WARNING)
p(story, "命名 Aspernolide D 没有对应主 docking 的 natlead 原始条目。后续材料将未命名 Aspergillus terreus 同源物的主 docking 分数二次标记为 Aspernolide D family；因此命名 Aspernolide D 不应继承那组三受体分数。", indent=False)

add_h2(story, "5.3 正式报告版本的使用规则")
bullets(story, [
    "根目录与 report_build 中多份 DOCX 为二进制重复副本，不构成新增研究或独立验证。",
    "报告叙事与源码、结果表冲突时，应优先采用保存的原始结果和 PDBQT pose，其次采用生成源码与修订文件。",
    "V2 的 11/12/10 靶点、原始 9,195 行与实际 9,099 模型输入、疾病模块的 0 显著模块/0 hub、V5 raw-score 溯源缺口均须披露。",
    "组合 synergy 和网络 proximity 结果是设计性假设，不是药理协同或显著网络接近性实测。",
])

add_h1(story, "六、候选状态与实验进入顺序")
p(story, "候选管理应以身份、可得性、安全性与证据层级为先，而不是以单一计算分数为先。以下分档替代旧版终榜；各档的“优先”均表示湿实验进入顺序，不表示已证实疗效。", indent=False)
story.extend(table(
    ["状态", "候选/候选组", "可采用的证据定位", "当前处理"],
    [["优先实验假设 A", "antcin K、antrodin B、Antrocinnamomin F", "樟芝菌丝体全粉 RCT 是物种/制剂级信息；Antrocinnamomin F 有计算和 pose 支撑", "antcin K、antrodin B 进入首批标准品；不宣称单体 RCT"],
     ["优先实验假设 A", "asiatic acid", "外部抗纤维化文献线索；无可比内部计算分", "文献驱动候选/比较对象进入初筛"],
     ["第二梯队 B", "Butyrolactone VI", "命名条目有保存 Vina pose；无功能或 MASH 实验", "首批 hit 后扩展"],
     ["第二梯队 B", "Anthraxin、Derrone", "计算与传统用途叙事；药材归属待复核", "先核 CID、来源和可得性"],
     ["条件性", "Alternaramide", "文献真实；肝方向、NF-kB 作用和安全性未决", "功能方向验证后再升降"],
     ["计算对照", "07H239-A、Alisiaquinol", "计算信号存在", "不可得性与毒性/醌类风险使其退出首批"],
     ["机制参照", "Versicolamide B", "家族机制线索", "不进入实验席位"],
     ["暂缓入榜", "未命名螺甾烷苷元、Aspernolide D 主 docking", "身份或评分归因不完整", "先完成身份和溯源纠正"]],
    [0.16, 0.24, 0.32, 0.28], "表 9　最终候选状态表"
))
callout(story, "证据层级提醒", "樟芝的 28 人信息对应菌丝体全粉与血清学终点，不能外推为 Antrocinnamomin F、antcin K 或 antrodin B 的单体临床疗效。asiatic acid 的外部纤维化文献也不能与内部 FINAL 数字机械比较。", SEM_WARNING)

add_h1(story, "七、下一步湿实验方案")
add_h2(story, "7.1 阶段 0：化学身份、纯度与可溶性门控")
p(story, "首批获取 antcin K、antrodin B、asiatic acid 与小檗碱；lovastatin 作为第二阳性对照。每个样品建立供应商、批号、COA、结构标识、纯度、溶解度、储液浓度和冻融记录。没有明确身份、纯度或稳定配制条件的候选不进入细胞实验。", indent=False)
story.extend(table(
    ["项目", "预设要求", "不通过时处理"],
    [["身份", "结构标识、COA、批号与来源可追溯", "停止采购/实验，先做身份与来源核对"],
     ["纯度", "建议不低于 95%", "不进入机制/动物阶段；必要时更换批次"],
     ["溶剂", "DMSO 终浓度不高于 0.1%", "调整浓度或停止该候选"],
     ["可溶性", "目标浓度无可见析出、vehicle 无异常", "不将假性暴露结果纳入 hit 判定"]],
    [0.18, 0.45, 0.37], "表 10　阶段 0 样品门控"
))

add_h2(story, "7.2 阶段 1：HepG2 脂变初筛")
story.extend(table(
    ["要素", "预设方案", "目的"],
    [["模型", "HepG2；PA/OA=2:1；总脂肪酸 0.25 mM；诱导 24–48 h", "建立可重复脂变表型"],
     ["浓度", "0.1、1、10、30 microM；先固定 vehicle", "建立效应与毒性窗口"],
     ["主读出", "细胞内 TG 定量", "定义脂质改善"],
     ["正交读出", "BODIPY 或油红 O；必要时两者", "排除单一 readout 偏差"],
     ["活力", "CCK-8 或 CellTiter-Glo", "识别以细胞损伤造成的表观 TG 下降"],
     ["对照", "小檗碱 10 microM；lovastatin 1 microM；等浓度 DMSO", "保证 assay 可解释性"],
     ["重复", "至少 3 次独立实验；每次每组至少 3 个技术复孔", "评估可重复性"]],
    [0.15, 0.58, 0.27], "表 11　阶段 1 脂变初筛设计"
))
callout(story, "预设 hit 标准", "相对脂变模型组，TG 下降不低于 30%，并且在满足此条件的最低有效浓度不高于 10 microM 时细胞活力不低于 80%。采用 30% 阈值，不沿用旧 roadmap 中的 20% 口径。", SEM_SUCCESS)
p(story, "停止规则：若 10 microM 或更低浓度使活力低于 80%，或 TG 改善仅伴随明显细胞损失出现，则不作为脂质改善 hit 推进；若溶解度、身份或批次一致性不满足门控，同样停止投入。", indent=False)

add_h2(story, "7.3 阶段 2：命中复验、方向与靶点假设")
bullets(story, [
    "在独立批次中复现 TG、BODIPY/油红 O 与活力结果，确认效应方向、剂量关系和重复性。",
    "使用 qPCR 或蛋白读出观察 FASN、SCD1、ACACA、SQLE 以及 COL1A1/COL1A2、ACTA2、TIMP1 等模块；这些变化只作为机制线索。",
    "对 FXR 或 THR-beta 假设使用报告基因或共激活因子体系区分激动/拮抗方向；QSAR 和 Vina 均不能替代该实验。",
    "若需要直接结合结论，在蛋白质量和化合物稳定性合格的条件下使用 SPR、MST、荧光偏振等正交实验，并将结合与功能分别报告。",
])

add_h2(story, "7.4 阶段 3–4：纤维化相关与体内合作")
p(story, "脂变 hit 不自动代表抗纤维化。通过阶段 2 的低毒 hit 可进入 TGF-beta 激活的 LX-2 或其他经验证肝星状细胞体系，考察胶原、ACTA2、TIMP1 与活力。只有脂变与纤维化相关模型均达到预设门槛的候选，才具备体内合作的依据。AMLN 小鼠或等效 MASH 模型应保持为外部合作项目，不计入当前项目已完成内容或既定承诺。", indent=False)

add_h1(story, "八、决策门、停止规则与对外结论")
story.extend(table(
    ["决策点", "进入条件", "停止/淘汰条件", "输出"],
    [["样品门控", "身份、COA、纯度、可溶性明确", "无身份、不可得、析出或 vehicle 异常", "可测试标准品清单"],
     ["脂变初筛", "TG 下降 >=30%，活力 >=80%，最低有效浓度 <=10 microM", "仅毒性相关下降或无重复性", "hit/非 hit 判定"],
     ["命中复验", "独立重复稳定，正交脂质 readout 一致", "批次不一致、剂量无方向", "可复现实验 hit"],
     ["机制验证", "功能方向与脂质表型相符", "报告基因/功能方向矛盾", "机制假设，不是机制定论"],
     ["纤维化相关", "低毒且出现纤维化轴改善线索", "无效或高毒", "体内合作候选池"],
     ["体内合作", "体外证据、初步暴露、资源与伦理可行", "只有计算分或单项细胞指标", "预注册体内方案"]],
    [0.17, 0.32, 0.28, 0.23], "表 12　go/no-go 决策门"
))
callout(story, "可对外使用的最终结论", "本项目完成了多条抗 MASH 天然产物计算优先级路线及其审计。V1 证明随机划分会高估对新骨架的预测能力；COCONUT/MTS 与 v5 仅是探索性筛选和候选治理；独立 THR-beta/FASN/SCD1 重建方法更严格，但 54 个候选无高置信域内分子。因此，所有候选均应定位为待实验检验的相对优先级假设，现有仓库不存在直接、完成、可追溯的抗 MASH 湿实验疗效证据。", SEM_ERROR)

add_h2(story, "8.1 发布前仍需披露或修复的问题")
bullets(story, [
    "GSE135251 应固定采用保存分组元数据的 NASH=155、总样本=216；README 的 141/202 口径不得继续作为结果引用。",
    "V1 不确定性有 pooled/test-only 双口径，图表必须标明数据子集、覆盖定义与校准来源；M5 的高覆盖同时披露小测试集和宽区间代价。",
    "COCONUT 的 12/11/10 靶点、9,195 原始行/9,099 实际模型输入、SQLE 未进入当前 QA/全库评分及 ACC1 缺失状态须在版本说明中区分。",
    "V5 修订表可追溯为历史表变换，但当前可见 raw-score 源码不能清洁重现历史分数；不得写成完整 rerun。",
    "组合 synergy 与网络 proximity 为设计假设，不是实测协同或显著网络证据。",
])

add_h1(story, "九、关键审计依据")
p(story, "本报告只整合既有项目文件、保存结果与已完成审计，不重跑 QSAR、docking、数据下载或湿实验。关键来源如下。", indent=False)
source_rows = [
    ["V1 表达与模型", "mash_research/results/tables/target_genes_validation.csv；gnn_metrics_v2.json；results/v6/conformal_calibration.json"],
    ["V1 对接与排序", "mash_research/docking/redock_validation.json；results/tables/herb_cwbcs_ranking_fix.csv"],
    ["COCONUT 扩展", "mash_research/results/v2/qsar_qa.json；module_summary.json；natural_multitarget_leaders_docking.csv"],
    ["候选治理", "mash_research/results/v5/final_unified_scores_fix.csv；最终候选清单_圆桌修订版.md"],
    ["独立重建", "mash_v2_new/results/tables/target_validation_new.csv；s3_qsar_metrics.json；s6_summary.json；src/s6_topsis.py"],
    ["审计与复现", "roundtable/judge_verdict.md；verify_repro/复现验证报告.md；paper/manuscript.md"],
]
story.extend(table(["类别", "关键文件"], source_rows, [0.22, 0.78], "表 13　关键审计依据"))
add_h2(story, "9.1 审计使用说明")
story.extend(table(
    ["范围", "本报告的处理规则"],
    [["纳入", "保存的结果表、源代码、修订文件、PDBQT 姿势、独立复现与圆桌审计材料"],
     ["未纳入为证据", "未经保存运行链支持的历史叙事、未完成的 LINCS 输出、未完成的湿实验计划"],
     ["未执行", "未重跑 QSAR、对接、数据下载、网络查询或湿实验；未改动任何原始研究文件"],
     ["使用方式", "可用于结题与实验决策；候选排序只能作为预注册湿实验优先级，不作为疗效证明"]],
    [0.22, 0.78], "表 14　报告审计范围与使用限制"
))
callout(story, "结题与后续研究的分界", "计算交付可以结题，但药效发现不能据此结题。只有在身份明确的化合物通过预设脂变、活力、方向性功能与纤维化相关门控后，才可更新其证据等级；在此之前，所有候选均保留为可被淘汰的实验假设。", SEM_INFO)
p(story, "报告生成仅新增本报告的 Markdown 源、Python 构建脚本、HTML 封面和 PDF 成品；没有改动任何原始研究数据、源代码、模型输出、对接结果或既有文档。", indent=False)


doc = TocDocTemplate(
    str(BODY_PDF), pagesize=A4, leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=2.1 * cm, bottomMargin=1.9 * cm,
    title=TITLE, author="Z.ai", creator="Z.ai", subject=SUBTITLE,
)
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print(f"Built body PDF: {BODY_PDF}")

if not COVER_PDF.exists():
    raise FileNotFoundError(f"Cover PDF not found: {COVER_PDF}")

A4_W, A4_H = 595.28, 841.89

def normalize(page):
    width, height = float(page.mediabox.width), float(page.mediabox.height)
    if abs(width - A4_W) > 0.3 or abs(height - A4_H) > 0.3:
        page.add_transformation(Transformation().scale(sx=A4_W / width, sy=A4_H / height))
        page.mediabox.lower_left = (0, 0)
        page.mediabox.upper_right = (A4_W, A4_H)
    return page

writer = PdfWriter()
writer.add_page(normalize(PdfReader(str(COVER_PDF)).pages[0]))
for page in PdfReader(str(BODY_PDF)).pages:
    writer.add_page(normalize(page))
writer.add_metadata({
    "/Title": TITLE,
    "/Author": "Z.ai",
    "/Creator": "Z.ai",
    "/Subject": SUBTITLE,
})
with open(FINAL_PDF, "wb") as out:
    writer.write(out)
print(f"Built final PDF: {FINAL_PDF}")
